// Curated list of family-friendly surprising facts. One is shown per day,
// rotating deterministically by day-of-year so everyone sees the same fact
// all day, and a different one tomorrow.

const FACTS = [
  'Honey never spoils — archaeologists have eaten 3,000-year-old honey from Egyptian tombs.',
  'Octopuses have three hearts and blue blood.',
  'A group of flamingos is called a "flamboyance."',
  'Wombat poop is cube-shaped.',
  'Bananas are berries — but strawberries are not.',
  'A bolt of lightning is hotter than the surface of the sun.',
  'Sharks existed before trees.',
  'Cows have best friends and get stressed when separated from them.',
  'A jiffy is an actual unit of time — 1/100th of a second.',
  'Sea otters hold hands while they sleep so they don\'t drift apart.',
  'Earth has more trees (3 trillion+) than the Milky Way has stars (~400 billion).',
  'A day on Venus is longer than a year on Venus.',
  'Hot water freezes faster than cold water in some conditions — it\'s called the Mpemba effect.',
  'Polar bears have black skin under their white fur.',
  'A snail can sleep for three years at a time.',
  'There are more possible games of chess than atoms in the observable universe.',
  'The shortest war in history lasted 38 to 45 minutes (Anglo-Zanzibar War, 1896).',
  'A blue whale\'s heart is so big a small child could swim through its arteries.',
  'Butterflies taste with their feet.',
  'Ants don\'t sleep — but they do take 250 tiny naps a day.',
  'Dolphins have names for each other.',
  'A group of pugs is called a "grumble."',
  'Pineapples take about two years to grow.',
  'Bees can recognize human faces.',
  'The Eiffel Tower can grow more than 6 inches taller in summer because the metal expands.',
  'Sloths can hold their breath longer than dolphins — up to 40 minutes.',
  'There are more atoms in a glass of water than glasses of water in all the oceans.',
  'Cats can\'t taste sweetness.',
  'A cloud can weigh more than a million pounds.',
  'The first oranges weren\'t orange — they were green.',
  'Goats have rectangular pupils.',
  'There\'s enough DNA in your body to stretch from the sun to Pluto and back — 17 times.',
  'A group of jellyfish is called a "smack."',
  'Penguins propose to their mates with a pebble.',
  'You can hear a blue whale\'s heartbeat from over two miles away.',
  'Avocados are technically fruits — and they\'re berries.',
  'The longest hiccupping fit lasted 68 years.',
  'A shrimp\'s heart is in its head.',
  'You\'re slightly taller in the morning than at night.',
  'Sea cucumbers can liquefy and re-form their bodies.',
  'A group of owls is called a "parliament."',
  'Crows can use tools and remember faces of people they don\'t like.',
  'Saturn would float in water if you had a tub big enough.',
  'Some turtles can breathe through their butts.',
  'A single strand of spider silk is stronger than steel of the same diameter.',
  'There\'s a planet that rains glass — sideways.',
  'Cashews grow on the bottom of an apple-shaped fruit called a cashew apple.',
  'The unicorn is the official national animal of Scotland.',
  'A group of porcupines is called a "prickle."',
  'Pigs cannot look up at the sky without lying down.',
  'The Hawaiian alphabet has only 13 letters.',
  'Bubble wrap was originally invented as wallpaper.',
  'Hummingbirds are the only birds that can fly backwards.',
  'A lightning bolt is about five times hotter than the surface of the sun.',
  'Honey bees have to visit about 2 million flowers to make one pound of honey.',
  'Sunflowers turn to follow the sun across the sky.',
  'A koala\'s fingerprints are nearly identical to a human\'s.',
  'There are more chickens than people on Earth.',
  'A dog\'s nose print is unique, just like a human fingerprint.',
  'Penguins\' knees are inside their bodies.',
  'A baby spider is called a spiderling.',
  'Watermelons are 92% water.',
  'A group of crows is called a "murder."',
  'Sneezes can travel up to 100 mph.',
  'Frogs absorb water through their skin instead of drinking it.',
  'Kangaroos can\'t walk backwards.',
  'A tomato has more genes than a human.',
  'You share 50% of your DNA with a banana.',
  'The smell of fresh-cut grass is a plant distress call.',
  'Octopuses can recognize individual humans — and play favorites.',
  'A baby giraffe falls about 6 feet when it\'s born.',
  'There are more stars in space than grains of sand on every beach on Earth.',
  'Cows can\'t walk down stairs (their knees don\'t bend the right way).',
  'Bananas grow upward, not downward.',
  'A group of unicorns would be called a "blessing."',
  'The dot on the letter "i" is called a tittle.',
  'You can\'t hum while holding your nose closed.',
  'A blue whale\'s tongue weighs as much as an elephant.',
  'Ostriches can run faster than horses.',
  'A small percentage of the static you see on an old TV with no signal is leftover radiation from the Big Bang.',
  'Tigers have striped skin, not just striped fur.',
];

export function factForToday(date = new Date()) {
  const startOfYear = new Date(date.getFullYear(), 0, 1);
  const dayOfYear = Math.floor((date - startOfYear) / 86_400_000);
  return FACTS[dayOfYear % FACTS.length];
}
